redis:
  url: "redis://localhost:6379/0"

sentry:
  url: # set in settings.local.yml

trogdir:
  scheme: http
  host: trogdir-api.dev
  port:
  script_name:
  version: v1
  access_id: # set in settings.local.yml
  secret_key: # set in settings.local.yml
  api_timeout: 300 # 5 min

biola_id_length: 10
